name: CD
on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Install library
        run: make install-dev

      - name: Deploy library
        run: make deploy
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Generate documentation
        run: make doc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cd
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
